apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: boutique
labels:
- pairs:
    app.kubernetes.io/part-of: online-boutique
resources:
- frontend.yaml
- adservice.yaml
- cartservice.yaml
- checkoutservice.yaml
- emailservice.yaml
- paymentservice.yaml
- productcatalogservice.yaml
- recommendationservice.yaml
- shippingservice.yaml
- currencyservice.yaml
- redis.yaml
- network-policies

images:
  - name: registry.digitalocean.com/idpreg/frontend
    newTag: sha-initial
  - name: registry.digitalocean.com/idpreg/adservice
    newTag: sha-initial
  - name: registry.digitalocean.com/idpreg/cartservice
    newTag: sha-initial
  - name: registry.digitalocean.com/idpreg/checkoutservice
    newTag: sha-initial
  - name: registry.digitalocean.com/idpreg/emailservice
    newTag: sha-initial
  - name: registry.digitalocean.com/idpreg/paymentservice
    newTag: sha-initial
  - name: registry.digitalocean.com/idpreg/productcatalogservice
    newTag: sha-initial
  - name: registry.digitalocean.com/idpreg/recommendationservice
    newTag: sha-initial
  - name: registry.digitalocean.com/idpreg/shippingservice
    newTag: sha-initial
  - name: registry.digitalocean.com/idpreg/currencyservice
    newTag: sha-initial

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all-deployments # Kustomize ignores this name and matches the target kind
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: idpreg
  target:
    kind: Deployment
images:
- name: registry.digitalocean.com/idpreg/adservice
  newName: registry.digitalocean.com/idpreg/adservice
  newTag: sha-4003c5430901a7541d602e9c13e0a286447da61e
- name: registry.digitalocean.com/idpreg/cartservice
  newName: registry.digitalocean.com/idpreg/cartservice
  newTag: sha-4003c5430901a7541d602e9c13e0a286447da61e
- name: registry.digitalocean.com/idpreg/checkoutservice
  newName: registry.digitalocean.com/idpreg/checkoutservice
  newTag: sha-4003c5430901a7541d602e9c13e0a286447da61e
- name: registry.digitalocean.com/idpreg/currencyservice
  newName: registry.digitalocean.com/idpreg/currencyservice
  newTag: sha-4003c5430901a7541d602e9c13e0a286447da61e
- name: registry.digitalocean.com/idpreg/emailservice
  newName: registry.digitalocean.com/idpreg/emailservice
  newTag: sha-4003c5430901a7541d602e9c13e0a286447da61e
- name: registry.digitalocean.com/idpreg/frontend
  newName: registry.digitalocean.com/idpreg/frontend
  newTag: sha-4003c5430901a7541d602e9c13e0a286447da61e
- name: registry.digitalocean.com/idpreg/paymentservice
  newName: registry.digitalocean.com/idpreg/paymentservice
  newTag: sha-4003c5430901a7541d602e9c13e0a286447da61e
- name: registry.digitalocean.com/idpreg/productcatalogservice
  newName: registry.digitalocean.com/idpreg/productcatalogservice
  newTag: sha-4003c5430901a7541d602e9c13e0a286447da61e
- name: registry.digitalocean.com/idpreg/recommendationservice
  newName: registry.digitalocean.com/idpreg/recommendationservice
  newTag: sha-4003c5430901a7541d602e9c13e0a286447da61e
- name: registry.digitalocean.com/idpreg/shippingservice
  newName: registry.digitalocean.com/idpreg/shippingservice
  newTag: sha-4003c5430901a7541d602e9c13e0a286447da61e
