---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: idpreg
  namespace: kyverno
spec:
  encryptedData:
    .dockerconfigjson: AgC0eJPJ4g57uCVJe7+y7N4fWj3j/oMgX1pWShlAoPeSDt+x9XtLY+w+rXEikiubaiOdSemh+TIjYE/UrvF4+4Zicxmz5e+S+FeemagOP/4TxFD/V4QTPFKT6RHnccmh5ULUAk5egndEaGf82l/3Cvq1AyfQ1Z0RcLWfkHboMuIQuVqo9l7Lyo+nffUJkJOXhEXTBGnofOqG+wbQ9b0Q0yTJEVLpgq4DeI6Juk2OAoWvjG8QCK2kHXKQOjiarYmksuIHyF81mBhRbCfKZRMnaiYNZfDDo3BbNT3lODChl7Zv3vZTZkKTLSRKwU+2jRqzwozOHPi7DdFN3f68the00EeO07uSKLDljbxarH+AV6ZTEzbl6BS06lS51WkwDJFQ+HUEZmGB+c6AMnpj2uXKBZi7iZD+n59Y7ELbwmh3jvz95af+yWSRLbsjx1zOtW+EMlNkGfY1LMuB7aUwwW1+jbQc3ZWfUTNBnFnE6k7CKRULHNYJPl001J/FR8JD4iGYV6Huf5CTnx10NxOZZHw8aP4/DSE1o2PIzzX25FG3pi4Ba2VA1pMxwdDLud7AgHuJjEMPzP8i359CVQfW4w2WdUEJ+HPatp6kzb3HSZBZ5cJfYcP/5XYsZeqGiIqJneBnxTSib2ilQWi5BLqhxEClBFMYQULHtu1UG/PxA2DtTBCIAnFDtlV3taa+FhcmU7Wcz//nA95gPxuhl1ED/8Xh7fat2NiXovK3iomz2n2vOfINHv33J6PquxKJT5trnysOcY5CNShTW3CpPVIep+5JWKuj0JF9w4F77w/QXULMFztIoy2GQPIHeSqlrpTxOq92cbir8+SuxNRx1/nRjRyVbBy1UHX/cp/ywHjmO63vaIOiqSqRNt/jwtKayckC80b9QS9opvJgsZcKWq7mzVq2X2MB+vEovEbpvlGyC5yhxdbdLadM0rckkCIdG+kgFQ92CNHjayQUJ3TKzUnkoR1Im43me5B5M83EduNbqqewOOFuYrfmmynxK6Er+t3PjmkVanY4K+hWnyTdOrc4htAG7xLQHbC7
  template:
    metadata:
      name: idpreg
      namespace: kyverno
    type: kubernetes.io/dockerconfigjson
