---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docr
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAf/Pr/E/liLmGGjzdFESopKpxHt64HO3XErVEEvD13rOtb9kT2XpyF4idwD2OJ8MQWddil7DEZJhDYPA5LkoSlzunc/GtfW6WYkVsia0eMhv9k7PzQFFs7itHIbj9RNwLoLUdvs5CG1wDCOZMhJ6ZJ+pSyxrY/ZBV5Xafan1SoGAM0lBg/oEvrGLTN229p+4vr2Bl6vaGANnoebVcX93w930DErPPG+hXkjd69esxaO+uB2g3xxdxsBs6HDEIYE8FYfYfkUZ8x+pwlFg3datzqRUf95UC4/A8YX+p8bijwM8uhrIf1LXm2UZ/LeyOWuifd7y2kXpyJkHuEeIpSGepMom+U/KXBd0dgfViU2WfBcxI0LUpd7Hc+IuPgCgc5rIzAweyJxmfar3Z/ykEI79FLjUOah5gTz2keNQ7SiAZihAkTIonBQU9Jsv+HDs+qILTlhy1kJJkOGUaz3t7Ga3Uyw7dBU0MdLs0tGd3wlaHhaWWANWJIsYScJoTELMY7ZQ+EIQEwkB5lIs6aplQ3ymGT7eK7QkXhSz499WGwu4eUO9MJfJuWb0m7bXdUX3gOh5cT3xo44qmxcy48wLObGBmXu9H4H0gOxxBBZTQLY6QxN9o4bQ+XKwEKmcack84UPI+Lvxuyz1GpMCtTvKNUcwmiAYfvVPyQjPHcXWduhewDYm1U17u91CYWcXSs4c70EDQ73AWmm/QjBRyMSZ5PAxPlTwRdomFytChnMiJ0FJ22uejkQh+lgOxjU/96LxeUkWamvsAsd+7DJAVuWtlMN1qZ/qyeJiRLlmd9aOK53SF8S1lOHlwBMtj1yGOz0E8t5LYI1TY2QfoEKR2Wzfx5pz8icrMlC+H0ZSg5aLsLQ2FpiR8ZO8rHHERbqJu1VlHwQL1zYhfXHWysNteQ9aCmUdBgcJO+qN/L5Io7tOr3J8LcOLxcCdUAeko=
  template:
    metadata:
      name: docr
      namespace: default
    type: kubernetes.io/dockerconfigjson
