apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: test-alert
  namespace: prometheus
  labels:
    release: prometheus

spec:

  groups:

  - name: test.rules

    rules:

    - alert: TestAlert

      expr: vector(1)

      for: 1m

      labels:
        severity: warning

      annotations:

        summary: "Test alert firing"

        description: "This is a GitOps test alert"