name: Terraform DOKS Main

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/bootstrap/**'
      - '.github/workflows/terraform-main.yml'
  workflow_dispatch:

jobs:
  terraform-bootstrap:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: terraform/bootstrap/
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.6
      - run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
      - run: terraform validate
      - run: terraform plan
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_do_spaces_access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          TF_VAR_do_spaces_secret_key: ${{ secrets.SPACES_SECRET_KEY }}
          TF_VAR_lb_ip: ${{ secrets.LB_IP }}
      - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
          TF_VAR_do_spaces_access_key: ${{ secrets.SPACES_ACCESS_KEY }}
          TF_VAR_do_spaces_secret_key: ${{ secrets.SPACES_SECRET_KEY }}
          TF_VAR_lb_ip: ${{ secrets.LB_IP }}
  